### ISSUE TITLE
Unable to build image (Waiting for ssh)

### ISSUE THREAD

**Issue by et-ent** [goffinet/packer-kvm#13]
I checked out the code and have tried a number of these and I am get to the same point.  The container starts up fine.  The ISO is downloaded and verified.  The VM starts up and is connected to.  The initial boot command with the provided kickstart is passed in.  Then the system waits for ssh to connect.  And the container just waits.  

To eliminate something I did I did a clean checkout of the repo and then ran: `./build.sh centos7.pkr.hcl` (the image I am trying to build in the end is a Centos base image)

Here is a sample log file:

`2023/05/31 20:32:56 Running builder: 
2023/05/31 20:32:56 [INFO] (telemetry) Starting builder 
2023/05/31 20:32:56 packer-builder-qemu plugin: Qemu path: /usr/bin/qemu-system-x86_64, Qemu Image path: /usr/bin/qemu-img
2023/05/31 20:32:56 ui: ==> qemu.centos7: Retrieving ISO
2023/05/31 20:32:56 ui: ==> qemu.centos7: Trying http://ftp.belnet.be/mirror/ftp.centos.org/7/isos/x86_64/CentOS-7-x86_64-Minimal-2009.iso
2023/05/31 20:32:56 packer-builder-qemu plugin: Acquiring lock for: http://ftp.belnet.be/mirror/ftp.centos.org/7/isos/x86_64/CentOS-7-x86_64-Minimal-2009.iso?checksum=sha256%3A07b94e6b1a0b0260b94c83d6bb76b26bf7a310dc78d7a9c7432809fb9bc6194a (/opt/packer_cache/e476ea1d3ef3c2e3966a7081ac4239cd5ae5e8a3.iso.lock)
2023/05/31 20:32:56 ui: ==> qemu.centos7: Trying http://ftp.belnet.be/mirror/ftp.centos.org/7/isos/x86_64/CentOS-7-x86_64-Minimal-2009.iso?checksum=sha256%3A07b94e6b1a0b0260b94c83d6bb76b26bf7a310dc78d7a9c7432809fb9bc6194a
2023/05/31 20:32:58 ui: ==> qemu.centos7: http://ftp.belnet.be/mirror/ftp.centos.org/7/isos/x86_64/CentOS-7-x86_64-Minimal-2009.iso?checksum=sha256%3A07b94e6b1a0b0260b94c83d6bb76b26bf7a310dc78d7a9c7432809fb9bc6194a => /opt/packer_cache/e476ea1d3ef3c2e3966a7081ac4239cd5ae5e8a3.iso
2023/05/31 20:32:58 packer-builder-qemu plugin: Leaving retrieve loop for ISO
2023/05/31 20:32:58 packer-builder-qemu plugin: No floppy files specified. Floppy disk will not be made.
2023/05/31 20:32:58 packer-builder-qemu plugin: No CD files specified. CD disk will not be made.
2023/05/31 20:32:58 packer-builder-qemu plugin: [INFO] Creating disk with Path: artifacts/qemu/centos7/packer-centos7 and Size: 40000M
2023/05/31 20:32:58 packer-builder-qemu plugin: Executing qemu-img: []string{"create", "-f", "qcow2", "artifacts/qemu/centos7/packer-centos7", "40000M"}
2023/05/31 20:32:58 packer-builder-qemu plugin: stdout: Formatting 'artifacts/qemu/centos7/packer-centos7', fmt=qcow2 cluster_size=65536 extended_l2=off compression_type=zlib size=41943040000 lazy_refcounts=off refcount_bits=16
2023/05/31 20:32:58 packer-builder-qemu plugin: stderr:
2023/05/31 20:32:58 packer-builder-qemu plugin: Found available port: 8578 on IP: 0.0.0.0
2023/05/31 20:32:58 ui: ==> qemu.centos7: Starting HTTP server on port 8578
2023/05/31 20:32:58 packer-builder-qemu plugin: Looking for available communicator (SSH, WinRM, etc) port between 2222 and 4444
2023/05/31 20:32:58 packer-builder-qemu plugin: Found available port: 2855 on IP: 127.0.0.1
2023/05/31 20:32:58 ui: ==> qemu.centos7: Found port for communicator (SSH, WinRM, etc): 2855.
2023/05/31 20:32:58 ui: ==> qemu.centos7: Looking for available port between 5900 and 6000 on 127.0.0.1
2023/05/31 20:32:58 packer-builder-qemu plugin: Looking for available port between 5900 and 6000 on 127.0.0.1
2023/05/31 20:32:58 packer-builder-qemu plugin: Found available port: 5951 on IP: 127.0.0.1
2023/05/31 20:32:58 packer-builder-qemu plugin: Found available VNC port: 5951 on IP: 127.0.0.1
2023/05/31 20:32:58 packer-builder-qemu plugin: Qemu --version output: QEMU emulator version 6.0.0
2023/05/31 20:32:58 packer-builder-qemu plugin: Copyright (c) 2003-2021 Fabrice Bellard and the QEMU Project developers
2023/05/31 20:32:58 packer-builder-qemu plugin: Qemu version: 6.0.0
2023/05/31 20:32:58 ui: ==> qemu.centos7: Starting VM, booting from CD-ROM
2023/05/31 20:32:58 ui:     qemu.centos7: The VM will be run headless, without a GUI. If you want to
    qemu.centos7: view the screen of the VM, connect via VNC without a password to
    qemu.centos7: vnc://127.0.0.1:5951
2023/05/31 20:32:58 packer-builder-qemu plugin: Qemu Builder has no floppy files, not attaching a floppy.
2023/05/31 20:32:58 ui: ==> qemu.centos7: Overriding default Qemu arguments with qemuargs template option...
2023/05/31 20:32:58 packer-builder-qemu plugin: Executing /usr/bin/qemu-system-x86_64: []string{"-vnc", "127.0.0.1:51", "-device", "virtio-net,netdev=user.0", "-m", "2048M", "-machine", "type=pc,accel=kvm", "-netdev", "user,id=user.0,hostfwd=tcp::2855-:22", "-drive", "file=artifacts/qemu/centos7/packer-centos7,if=virtio,cache=none,discard=unmap,format=qcow2", "-drive", "file=/opt/packer_cache/e476ea1d3ef3c2e3966a7081ac4239cd5ae5e8a3.iso,media=cdrom", "-boot", "once=d", "-name", "packer-centos7", "-smp", "2"}
2023/05/31 20:32:58 packer-builder-qemu plugin: Started Qemu. Pid: 135
2023/05/31 20:33:00 ui: ==> qemu.centos7: Waiting 40s for boot...
2023/05/31 20:33:40 ui: ==> qemu.centos7: Connecting to VM via VNC (127.0.0.1:5951)
2023/05/31 20:33:40 packer-builder-qemu plugin: Connected to VNC desktop: QEMU (packer-centos7)
2023/05/31 20:33:40 ui: ==> qemu.centos7: Typing the boot command over VNC...
2023/05/31 20:33:40 packer-builder-qemu plugin: Special code '<up>' found, replacing with: 0xFF52
2023/05/31 20:33:41 packer-builder-qemu plugin: [INFO] Waiting 1s
2023/05/31 20:33:42 packer-builder-qemu plugin: Special code '<tab>' found, replacing with: 0xFF09
2023/05/31 20:33:42 packer-builder-qemu plugin: [INFO] Waiting 1s
2023/05/31 20:33:43 packer-builder-qemu plugin: Sending char ' ', code 0x20, shift false
2023/05/31 20:33:43 packer-builder-qemu plugin: Sending char 'n', code 0x6E, shift false
2023/05/31 20:33:43 packer-builder-qemu plugin: Sending char 'e', code 0x65, shift false
2023/05/31 20:33:43 packer-builder-qemu plugin: Sending char 't', code 0x74, shift false
2023/05/31 20:33:44 packer-builder-qemu plugin: Sending char '.', code 0x2E, shift false
2023/05/31 20:33:44 packer-builder-qemu plugin: Sending char 'i', code 0x69, shift false
2023/05/31 20:33:44 packer-builder-qemu plugin: Sending char 'f', code 0x66, shift false
2023/05/31 20:33:44 packer-builder-qemu plugin: Sending char 'n', code 0x6E, shift false
2023/05/31 20:33:44 packer-builder-qemu plugin: Sending char 'a', code 0x61, shift false
2023/05/31 20:33:45 packer-builder-qemu plugin: Sending char 'm', code 0x6D, shift false
2023/05/31 20:33:45 packer-builder-qemu plugin: Sending char 'e', code 0x65, shift false
2023/05/31 20:33:45 packer-builder-qemu plugin: Sending char 's', code 0x73, shift false
2023/05/31 20:33:45 packer-builder-qemu plugin: Sending char '=', code 0x3D, shift false
2023/05/31 20:33:45 packer-builder-qemu plugin: Sending char '0', code 0x30, shift false
2023/05/31 20:33:46 packer-builder-qemu plugin: Sending char ' ', code 0x20, shift false
2023/05/31 20:33:46 packer-builder-qemu plugin: Sending char 'b', code 0x62, shift false
2023/05/31 20:33:46 packer-builder-qemu plugin: Sending char 'i', code 0x69, shift false
2023/05/31 20:33:46 packer-builder-qemu plugin: Sending char 'o', code 0x6F, shift false
2023/05/31 20:33:46 packer-builder-qemu plugin: Sending char 's', code 0x73, shift false
2023/05/31 20:33:47 packer-builder-qemu plugin: Sending char 'd', code 0x64, shift false
2023/05/31 20:33:47 packer-builder-qemu plugin: Sending char 'e', code 0x65, shift false
2023/05/31 20:33:47 packer-builder-qemu plugin: Sending char 'v', code 0x76, shift false
2023/05/31 20:33:47 packer-builder-qemu plugin: Sending char 'n', code 0x6E, shift false
2023/05/31 20:33:47 packer-builder-qemu plugin: Sending char 'a', code 0x61, shift false
2023/05/31 20:33:48 packer-builder-qemu plugin: Sending char 'm', code 0x6D, shift false
2023/05/31 20:33:48 packer-builder-qemu plugin: Sending char 'e', code 0x65, shift false
2023/05/31 20:33:48 packer-builder-qemu plugin: Sending char '=', code 0x3D, shift false
2023/05/31 20:33:48 packer-builder-qemu plugin: Sending char '0', code 0x30, shift false
2023/05/31 20:33:48 packer-builder-qemu plugin: Sending char ' ', code 0x20, shift false
2023/05/31 20:33:49 packer-builder-qemu plugin: Sending char 't', code 0x74, shift false
2023/05/31 20:33:49 packer-builder-qemu plugin: Sending char 'e', code 0x65, shift false
2023/05/31 20:33:49 packer-builder-qemu plugin: Sending char 'x', code 0x78, shift false
2023/05/31 20:33:49 packer-builder-qemu plugin: Sending char 't', code 0x74, shift false
2023/05/31 20:33:49 packer-builder-qemu plugin: Sending char ' ', code 0x20, shift false
2023/05/31 20:33:50 packer-builder-qemu plugin: Sending char 'k', code 0x6B, shift false
2023/05/31 20:33:50 packer-builder-qemu plugin: Sending char 's', code 0x73, shift false
2023/05/31 20:33:50 packer-builder-qemu plugin: Sending char '=', code 0x3D, shift false
2023/05/31 20:33:50 packer-builder-qemu plugin: Sending char 'h', code 0x68, shift false
2023/05/31 20:33:50 packer-builder-qemu plugin: Sending char 't', code 0x74, shift false
2023/05/31 20:33:51 packer-builder-qemu plugin: Sending char 't', code 0x74, shift false
2023/05/31 20:33:51 packer-builder-qemu plugin: Sending char 'p', code 0x70, shift false
2023/05/31 20:33:51 packer-builder-qemu plugin: Sending char ':', code 0x3A, shift true
2023/05/31 20:33:51 packer-builder-qemu plugin: Sending char '/', code 0x2F, shift false
2023/05/31 20:33:52 packer-builder-qemu plugin: Sending char '/', code 0x2F, shift false
2023/05/31 20:33:52 packer-builder-qemu plugin: Sending char '1', code 0x31, shift false
2023/05/31 20:33:52 packer-builder-qemu plugin: Sending char '0', code 0x30, shift false
2023/05/31 20:33:52 packer-builder-qemu plugin: Sending char '.', code 0x2E, shift false
2023/05/31 20:33:52 packer-builder-qemu plugin: Sending char '0', code 0x30, shift false
2023/05/31 20:33:53 packer-builder-qemu plugin: Sending char '.', code 0x2E, shift false
2023/05/31 20:33:53 packer-builder-qemu plugin: Sending char '2', code 0x32, shift false
2023/05/31 20:33:53 packer-builder-qemu plugin: Sending char '.', code 0x2E, shift false
2023/05/31 20:33:53 packer-builder-qemu plugin: Sending char '2', code 0x32, shift false
2023/05/31 20:33:53 packer-builder-qemu plugin: Sending char ':', code 0x3A, shift true
2023/05/31 20:33:54 packer-builder-qemu plugin: Sending char '8', code 0x38, shift false
2023/05/31 20:33:54 packer-builder-qemu plugin: Sending char '5', code 0x35, shift false
2023/05/31 20:33:54 packer-builder-qemu plugin: Sending char '7', code 0x37, shift false
2023/05/31 20:33:54 packer-builder-qemu plugin: Sending char '8', code 0x38, shift false
2023/05/31 20:33:55 packer-builder-qemu plugin: Sending char '/', code 0x2F, shift false
2023/05/31 20:33:55 packer-builder-qemu plugin: Sending char 'h', code 0x68, shift false
2023/05/31 20:33:55 packer-builder-qemu plugin: Sending char 't', code 0x74, shift false
2023/05/31 20:33:55 packer-builder-qemu plugin: Sending char 't', code 0x74, shift false
2023/05/31 20:33:55 packer-builder-qemu plugin: Sending char 'p', code 0x70, shift false
2023/05/31 20:33:56 packer-builder-qemu plugin: Sending char '/', code 0x2F, shift false
2023/05/31 20:33:56 packer-builder-qemu plugin: Sending char 'c', code 0x63, shift false
2023/05/31 20:33:56 packer-builder-qemu plugin: Sending char 'e', code 0x65, shift false
2023/05/31 20:33:56 packer-builder-qemu plugin: Sending char 'n', code 0x6E, shift false
2023/05/31 20:33:56 packer-builder-qemu plugin: Sending char 't', code 0x74, shift false
2023/05/31 20:33:57 packer-builder-qemu plugin: Sending char 'o', code 0x6F, shift false
2023/05/31 20:33:57 packer-builder-qemu plugin: Sending char 's', code 0x73, shift false
2023/05/31 20:33:57 packer-builder-qemu plugin: Sending char '7', code 0x37, shift false
2023/05/31 20:33:57 packer-builder-qemu plugin: Sending char '-', code 0x2D, shift false
2023/05/31 20:33:57 packer-builder-qemu plugin: Sending char 'k', code 0x6B, shift false
2023/05/31 20:33:58 packer-builder-qemu plugin: Sending char 'i', code 0x69, shift false
2023/05/31 20:33:58 packer-builder-qemu plugin: Sending char 'c', code 0x63, shift false
2023/05/31 20:33:58 packer-builder-qemu plugin: Sending char 'k', code 0x6B, shift false
2023/05/31 20:33:58 packer-builder-qemu plugin: Sending char 's', code 0x73, shift false
2023/05/31 20:33:58 packer-builder-qemu plugin: Sending char 't', code 0x74, shift false
2023/05/31 20:33:59 packer-builder-qemu plugin: Sending char 'a', code 0x61, shift false
2023/05/31 20:33:59 packer-builder-qemu plugin: Sending char 'r', code 0x72, shift false
2023/05/31 20:33:59 packer-builder-qemu plugin: Sending char 't', code 0x74, shift false
2023/05/31 20:33:59 packer-builder-qemu plugin: Sending char '.', code 0x2E, shift false
2023/05/31 20:33:59 packer-builder-qemu plugin: Sending char 'c', code 0x63, shift false
2023/05/31 20:34:00 packer-builder-qemu plugin: Sending char 'f', code 0x66, shift false
2023/05/31 20:34:00 packer-builder-qemu plugin: Sending char 'g', code 0x67, shift false
2023/05/31 20:34:00 packer-builder-qemu plugin: Special code '<enter>' found, replacing with: 0xFF0D
2023/05/31 20:34:00 packer-builder-qemu plugin: [INFO] Waiting 1s
2023/05/31 20:34:01 ui:     qemu.centos7: Not using a NetBridge -- skipping StepWaitGuestAddress
2023/05/31 20:34:01 ui: ==> qemu.centos7: Using SSH communicator to connect: 127.0.0.1
2023/05/31 20:34:01 packer-builder-qemu plugin: [INFO] Waiting for SSH, up to timeout: 30m0s
2023/05/31 20:34:01 ui: ==> qemu.centos7: Waiting for SSH to become available...
2023/05/31 20:34:01 packer-builder-qemu plugin: [INFO] Attempting SSH connection to 127.0.0.1:2855...
2023/05/31 20:34:01 packer-builder-qemu plugin: [DEBUG] reconnecting to TCP connection for SSH
2023/05/31 20:34:01 packer-builder-qemu plugin: [DEBUG] handshaking with SSH
2023/05/31 20:34:20 packer-builder-qemu plugin: [DEBUG] SSH handshake err: ssh: handshake failed: read tcp 127.0.0.1:58790->127.0.0.1:2855: read: connection reset by peer
2023/05/31 20:34:27 packer-builder-qemu plugin: [INFO] Attempting SSH connection to 127.0.0.1:2855...
2023/05/31 20:34:27 packer-builder-qemu plugin: [DEBUG] reconnecting to TCP connection for SSH
2023/05/31 20:34:27 packer-builder-qemu plugin: [DEBUG] handshaking with SSH
2023/05/31 20:34:27 packer-builder-qemu plugin: [DEBUG] SSH handshake err: ssh: handshake failed: read tcp 127.0.0.1:44574->127.0.0.1:2855: read: connection reset by peer
2023/05/31 20:34:34 packer-builder-qemu plugin: [INFO] Attempting SSH connection to 127.0.0.1:2855...
2023/05/31 20:34:34 packer-builder-qemu plugin: [DEBUG] reconnecting to TCP connection for SSH
2023/05/31 20:34:34 packer-builder-qemu plugin: [DEBUG] handshaking with SSH
2023/05/31 20:34:34 packer-builder-qemu plugin: [DEBUG] SSH handshake err: ssh: handshake failed: read tcp 127.0.0.1:45896->127.0.0.1:2855: read: connection reset by peer
2023/05/31 20:34:41 packer-builder-qemu plugin: [INFO] Attempting SSH connection to 127.0.0.1:2855...
2023/05/31 20:34:41 packer-builder-qemu plugin: [DEBUG] reconnecting to TCP connection for SSH
2023/05/31 20:34:41 packer-builder-qemu plugin: [DEBUG] handshaking with SSH
2023/05/31 20:34:41 packer-builder-qemu plugin: [DEBUG] SSH handshake err: ssh: handshake failed: read tcp 127.0.0.1:45922->127.0.0.1:2855: read: connection reset by peer
`

**Comment by stanlog** [comment]
Hello, same result at home.

```
==> qemu.debian12: Overriding default Qemu arguments with qemuargs template option...
==> qemu.debian12: Waiting 15s for boot...
==> qemu.debian12: Connecting to VM via VNC (127.0.0.1:5900)
==> qemu.debian12: Typing the boot commands over VNC...
    qemu.debian12: Not using a NetBridge -- skipping StepWaitGuestAddress
==> qemu.debian12: Using SSH communicator to connect: 127.0.0.1
==> qemu.debian12: Waiting for SSH to become available...
==> qemu.debian12: Timeout waiting for SSH.
==> qemu.debian12: Deleting output directory...
Build 'qemu.debian12' errored after 32 minutes 13 seconds: Timeout waiting for SSH.

==> Wait completed after 32 minutes 13 seconds
```

**Comment by goffinet** [comment]
Hello,

I have updated the https://hub.docker.com/r/goffinet/packer-qemu image build used in the script build.sh and now it is working.

**Comment by et-ent** [comment]
Maybe I am missing something but I don't see any changes to the code in the repo or any changes to the docker hub?

**Comment by goffinet** [comment]
The image has been rebuilt and released with the latest packer and qemu softwares.
