### ISSUE TITLE
Suggestion to use local mirror for fedora34 template

### ISSUE THREAD

**Issue by avnes** [goffinet/packer-kvm#4]
Hi

Thanks for merging the template for fedora34. I appreciate that. While I was building my own boxes with Fedora 34, I discovered that the url used in fedora34-kickstart.cfg sometimes caused RPM files not to be downloaded. I am not sure why this happened, but the workaround tuned out to be to use a more local mirror than using the mirror selector http://www.mirrorservice.org/sites/dl.fedoraproject.org/pub/fedora/linux/releases/34/Everything/x86_64/os/

So the workaround for me was to update fedora34-kickstart.cfg with:

`url --url="https://mirrors.dotsrc.org/fedora-buffet/fedora/linux/releases/34/Everything/x86_64/os/"`

I suggest you use a URL that is local to you.

**Comment by goffinet** [comment]
Hi,
https://download.fedoraproject.org/pub/fedora/linux/releases/ is preferred.
