### ISSUE TITLE
Script define-guest-images.sh does not exist

### ISSUE THREAD

**Issue by lisenet** [goffinet/packer-kvm#7]
The following commands should use `./define-guest-image.sh` and not `./define-guest-images.sh`
```
sudo ./define-guest-images.sh c1 centos7
sudo ./define-guest-images.sh u1 bionic
```

**Comment by goffinet** [comment]
This script exists in the repo https://github.com/goffinet/virt-scripts.

**Comment by lisenet** [comment]
I can't see `define-guest-images.sh` I'm afraid, can you drop me a direct link to the script in that repo please?

**Comment by goffinet** [comment]
https://github.com/goffinet/virt-scripts/blob/master/define-guest-image.sh

**Comment by goffinet** [comment]
Thank you @lisenet, I fixed the doc.

**Comment by lisenet** [comment]
Thanks. You finally found the typo didn't you.
