### ISSUE TITLE
Updating packages twice?

### ISSUE THREAD

**Issue by lisenet** [goffinet/packer-kvm#8]
You have package updates configured in your kickstart templates under the post section which makes sense, but then you also use an ansible playbook to update packages again as part of provisioner's run. Why?

**Comment by goffinet** [comment]
Yes. You are right. But why not ? And if I want to be sure that package update is done in the playbook (that I can re-use in other contexts) ?

**Comment by lisenet** [comment]
It's your design and your scripts, I'm just curious as to why you'd do package updates twice in a matter of moments, seems redundant to me. If the reason is `But why not ?` then fair enough, no worries. 

Since you already utilise ansible and, as you said, can re-use playbooks in other contexts, it would make more sense to dedicate this task to ansible (which gets run as a post-processor anyway) and remove package updates from kickstart.
